src/Data/Morpheus/Validation/Selection.hs
The project doesn't compile under GHC 8.6, but it only needs one small change to do so. This commit addresses the `MonadFail` changes in 8.6.
=> GHC 8.6 Support

README.md
I followed the tutorial in `README.md` of the repo, to find the API server returns an error claiming:
> "Cannot query field \"fullname\" on type \"Deity\"
This was because the correct field name was not `fullname` but `fullName`.
=> Correct case in README.md

README.md, changelog.md, src/Data/Morpheus/Types/Internal/Value.hs
Extend `convertToJSONName` and `convertToHaskellName`  to handle all Haskell 2010 _reservedid_.
A list of reserved keywords in Haskell 2010 can be found [here](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#TBL-103-3-1). The code preserves the order listed in the original language spec.
=> Feature/Handle Reserved Names #207

examples/Main.hs, src/Data/Morpheus/Document.hs, src/Data/Morpheus/Resolve/Resolve.hs
For cases where a `GQLRootResolver` may require for example a database
connection.
Don't know if this is preferable or idiomatic, but it helps my particular use case.
Maybe expose another function `toGraphQLDocument . Identity` from `Data.Morpheus.Document`?
=> Change `toGraphQLDocument` to accept `Proxy`

README.md, docs/index.md
Fixed a small typo in docs (website) and readme
=> Fix Graphql typo in README and docs

changelog.md, src/Data/Morpheus/Error/Selection.hs, src/Data/Morpheus/Execution/Server/Encode.hs, src/Data/Morpheus/Execution/Server/Resolve.hs, src/Data/Morpheus/Schema/SchemaAPI.hs, src/Data/Morpheus/Types.hs, src/Data/Morpheus/Types/GQLType.hs, src/Data/Morpheus/Types/Internal/Resolving.hs, src/Data/Morpheus/Types/Internal/Resolving/Resolver.hs, test/Feature/Holistic/API.hs
@smatting  @dandoh  @theobat so, i am not great advocate of sharing internal `AST` (for now it is not stabile yet). but some of you asked it. so exposed `unsafeInternalContext` , the code depend on it may break even on minor version changing,  therefore is called `unsafe` .
another use of this feature can be debugging, you can just print out `AST`, to understand why something does not works.
```hs
data Context = Context {
currentSelection :: (Name,ValidSelection),
schema :: Schema,
operation :: ValidOperation
} deriving (Show)
-- lookup context in Resolver
unsafeInternalContext :: (Monad m, LiftOperation o) => Resolver o e m Context
```
so you can use it as follows:
```hs
resolveUser :: ResolveQ EVENT IO User
resolveUser = do 
Context { currentSelection, schema, operation } <- …
```
=> Feature/User can get internal Context of Resolver

README.md
- The Graphql Schema in the README was not parsing correctly. 
- And the Example could not be find the `Undefined` type and constructor.
=> Typo fixes for the schema README example to make it parse correctly

README.md, changelog.md, docs/index.md, examples/src/Client/Client.hs, src/Data/Morpheus/Execution/Client/Selection.hs
Closes #399
@nalchevanidze I tried the change you recommended in the issue, but it seems that change is moving the generated types into different module namespaces. This was breaking the example in `Client.hs` where it could no longer find the generated types. I wasn't sure if you wanted them in different namespaces and.. I wasn't sure how to fix the compilation issues if so.
I figured out this change prefixes the data constructors with the type name.
=> Prefix enum's data constructors with the type name.

morpheus-graphql-core/src/Data/Morpheus/Types/Internal/Resolving/Resolver.hs, src/Data/Morpheus/Types.hs
This PR is meant to fix the absence of the Context datatype in Data.Morpheus.Types
Importing the context directly from the morpheus-graphql-core module creates mismatch between other types afterwards (Resolver, etc...). So this is required in order to access `currentSelection` within the Context
=> fix: unexported Context render unsafeInternalContext unusable

morpheus-graphql-client/src/Data/Morpheus/Client.hs, src/Data/Morpheus/Document.hs
Changed `defineByDocumentFile`, `defineByIntrospectionFile`,
`importGQLDocument`, `importGQLDocumentWithNamespace`, to take the type
synonym FilePath instead of String.
r/t https://github.com/morpheusgraphql/morpheus-graphql/issues/518
=> change types String to FilePath

src/Data/Morpheus/Types.hs
Hello!
I noticed that release 0.15.0 says
> GQLType exposes typeOptions to modify labels: typeOptions :: f a -> GQLTypeOptions
But I could not use it as it does not seem to be exposed. At least not when importing `Data.Morpheus.Types`. The haddock seems to confirm this as it only shows the methods `description` and `implements`: http://hackage.haskell.org/package/morpheus-graphql-0.15.0/docs/Data-Morpheus-Types.html
This PR should export all the methods, but perhaps it's overkill and more than desired. Happy to make any changes.
Thank you!
=> Export all methods for the GQLType class

morpheus-graphql-examples-scotty/morpheus-graphql-examples-scotty.cabal, morpheus-graphql-examples-scotty/package.yaml, morpheus-graphql-examples-scotty/src/Server/Fraxl/API.hs, morpheus-graphql-examples-scotty/src/Server/Fraxl/FakeDB.hs, morpheus-graphql-examples-scotty/src/Server/Scotty.hs, morpheus-graphql-examples-scotty/src/Server/Utils.hs, stack-11.10.yaml, stack-12.16.yaml, stack-14.14.yaml, stack-15.3.yaml, stack-16.2.yaml, stack.yaml
This is an example of using fraxl to batch database requests, which prevents the N+1 queries problem.  Related to the conversation in #348 
Probably a lot of room for improvement here - eagerly awaiting feedback/corrections
=> Example of using fraxl library for request batching

changelog.md, morpheus-graphql-client/changelog.md, morpheus-graphql-client/src/Data/Morpheus/Client.hs, src/Data/Morpheus/Document.hs
It is important to always call `qAddDependentFile` before reading a file in TH, as it allows allows GHC to decide whether to rebuild a module or not. Without `qAddDependentFile`, GHC will not rebuild the module if the file TH read has changed but the module file has not. With `qAddDependentFile`, GHC will rebuild the module if either file changed.
This is especially maddening if the code which loads the schema file and the resolvers are in a different modules. If I modify the name of something in the schema file and I modify the resolvers to match, I will get a compilation error telling me that the new names are not valid, and that I should be using the old names! The workaround is to make a dummy whitespace change to the module which loads the schema, thus forcing GHC to rebuild that …
=> rebuild when the schema changes

changelog.md, src/Data/Morpheus/Server/Types/GQLType.hs, src/Data/Morpheus/Server/Types/SchemaT.hs, test/Feature/TypeCategoryCollision/Fail/failOnColision/response.json, test/Feature/TypeCategoryCollision/Success/API.hs
fixes #558
This is a first draft. I don't have much experience on large Haskell projects, so I just wanted to get this up and get a conversation going. 
It seems inefficient to `upack` and apply the modifier then `pack` again, but I'm not exactly sure what the implications are of `typeNameModifier :: TypeName -> TypeName`.
I do not understand what `proxy` is doing in the code, so could I please have a bit of an explanation about that?
Also, I think I'll need more direction on writing tests for this change.
Thanks in advance for the feedback!
=> Add typeNameModifier to GQLTypeOptions

morpheus-graphql-client/changelog.md, morpheus-graphql-client/src/Data/Morpheus/Client.hs
This enables using utilities such as https://hackage.haskell.org/package/file-embed-0.0.13.0/docs/Data-FileEmbed.html#v:makeRelativeToProject
which can be used to work around file path issues when using multi package projects.
Specifically, if I run `stack repl subproject` which uses `defineByDocumentFile` it fails as the path is calculated differently via `stack repl` as compared to when you run the code or run it with tests. This issue also breaks haskell language server, as it relies on `stack repl` as well.
This changes enables using `makeRelativeToProject` which will hopefully make everything work. ~~Currently I am just putting this up to test that it does fix it.~~ Indeed this does fix the issue.
This is ready for review.
=> Add defineBy*File' variant to client that takes a Q FilePath

README.md
I was trying to setup Morpheus and followed the readme. I ended up getting the following error on `stack build`
```
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for morpheus-graphql-0.17.0:
morpheus-graphql-app must match >=0.17.0 && <0.18.0, but the stack configuration has no specified version  (latest matching
version is 0.17.0)
morpheus-graphql-core-0.12.0 from stack configuration does not match >=0.17.0 && <0.18.0  (latest matching version
is 0.17.0)
needed due to insurance-0.1.0.0 -> morpheus-graphql-0.17.0
Some different approaches to resolving this:
* Recommended action: try adding the following to your extra-deps in /Users/psilospore/develop/someproject/stack.yaml:
- …
```
=> Update Readme to add extra-deps for app and core

src/Data/Morpheus/Server/Types/GQLType.hs, src/Data/Morpheus/Types.hs
The currently published version of `morpheus-graphql` doesn't export any way to actually use `GQLTypeOptions`. This PR fixes that, and adds a little additional documentation:
=> Fix export of GQLTypeOptions and document it a bit.

morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Aeson.hs, morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Client.hs, morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Type.hs, morpheus-graphql-client/src/Data/Morpheus/Client/Internal/TH.hs
When generating the code for different queries that share the same
schema, morphreus tries to emit Aeson instances multiple times, which
does not work.
With this change, before generating a the instance, it will lookup
if it was declared already and avoid doing so.
This also helps when you want to take over and declare some things
manualy and let morpheus do the rest.
Additionally, this add a `omitNulls` pass to the generated Aeson object.
When sending the object for a type with lots of nullables, this reduces
significantly the request size.
=> fix(client): avoid generating duplicated Aeson instances

morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Aeson.hs, morpheus-graphql-client/src/Data/Morpheus/Client/Internal/TH.hs, morpheus-graphql-client/test/Case/Enum/Test.hs, morpheus-graphql-client/test/Case/Enum/response.json, morpheus-graphql-client/test/Case/Enum/schema.gql
Currently, the instances for an enum with a single filed are generated as
```gql
enum Planet {
Earth
}
```
```haskell
data Planet = PlanetEarth deriving (Generic, Show, Eq)
instance ToJSON Planet where
-- Notice it uses the type name here and not the constructor name
toJSON Planet = omitNulls []
instance FromJSON Planet where
fromJSON = withObject "Earth" (\v -> pure Earth)
```
I attempted a fix in this PR, which instead generates the instances as
```haskell
data Planet = PlanetEarth deriving (Generic, Show, Eq)
instance ToJSON Planet where
toJSON = \case PlanetEarth -> "Earth"
instance FromJSON Planet where
fromJSON = 
= \case
"Earth" -> pure PlanetEarth
v -> fail ((show v) <> " is Not Valid Union Constructor")
```
~But notice that the ToJSON and FromJSON instances after the fix don't …
=> Fix JSON instances for enums with a single variant.

morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/Name.hs, morpheus-graphql-server/src/Data/Morpheus/Server/Types.hs, morpheus-graphql-server/src/Data/Morpheus/Server/Types/GQLType.hs, morpheus-graphql-server/test/Feature/Directive/Definition.hs, morpheus-graphql-server/test/Feature/Directive/EnumVisitor.hs, morpheus-graphql-server/test/Feature/Directive/FieldVisitor.hs
- exposes `fieldDirective'` and `enumDirective'` using type checked template Haskell names
=> type checked directive locations

examples/yesod-pubsub/client/src/index.js
Yesod-pubsub example had a minor issue where the client was sending a malformed subscription request.
=> Fix Yesod ws example subscription
