README.md

For the initial release, document how to use the library.

Add getting started to readme

---

README.md
_site/errors.md
example/src/Example/Mythology.hs
example/src/Example/Schema.hs
morpheus/src/Data/Morpheus.hs
morpheus/src/Data/Morpheus/Error/Subscription.hs
morpheus/src/Data/Morpheus/Kind.hs
morpheus/src/Data/Morpheus/Kind/GQLSubscription.hs
morpheus/src/Data/Morpheus/Parser/Parser.hs
morpheus/src/Data/Morpheus/Parser/Subscription.hs
morpheus/src/Data/Morpheus/PreProcess/PreProcess.hs
morpheus/src/Data/Morpheus/Schema/Internal/Types.hs
morpheus/src/Data/Morpheus/Schema/Schema.hs
morpheus/src/Data/Morpheus/Types/Query/Operator.hs
morpheus/src/Data/Morpheus/Types/Types.hs
morpheus/test/TestAPI.hs

Initial work on #113. Largely just a copy/paste/replace job from mutation → subscription.

Feature/add Interface for Subscriptions (without functionality)

---

changelog.md
examples/Deprecated/API.hs
src/Data/Morpheus/Error/Input.hs
src/Data/Morpheus/Kind/GQLScalar.hs
src/Data/Morpheus/Kind/GQLType.hs
src/Data/Morpheus/Types/ID.hs
src/Data/Morpheus/Types/Internal/Data.hs
src/Data/Morpheus/Validation/Input/Object.hs

Feature/ Support scalar type ID

---

.travis.yml
specifications.md
stack-11.10.yaml
stack-13.15.yaml
stack-13.24.yaml

@krisajenkins  there is also version that you use for your project

Travis checks GHC: 8.4.3, 8.6.4 , 8.6.5

---

changelog.md
examples/index.html
src/Data/Morpheus/Resolve/Encode.hs
src/Data/Morpheus/Resolve/Resolve.hs
src/Data/Morpheus/Server.hs
src/Data/Morpheus/Server/Apollo.hs
src/Data/Morpheus/Server/ClientRegister.hs
src/Data/Morpheus/Types/Internal/Stream.hs
src/Data/Morpheus/Types/Internal/WebSocket.hs
test/Feature/Holistic/API.hs
test/Feature/WrappedTypeName/API.hs

Subscriptions/accept new apollo Subprotocols and fix Subscription Handling

---

changelog.md
examples/Main.hs
package.yaml
src/Data/Morpheus/Document.hs
src/Data/Morpheus/Resolve/Introspect.hs
src/Data/Morpheus/Resolve/Resolve.hs
src/Data/Morpheus/Schema/Directive.hs
src/Data/Morpheus/Schema/DirectiveLocation.hs
src/Data/Morpheus/Schema/EnumValue.hs
src/Data/Morpheus/Schema/Field.hs
src/Data/Morpheus/Schema/InputValue.hs
src/Data/Morpheus/Schema/Schema.hs
src/Data/Morpheus/Schema/Type.hs
src/Data/Morpheus/Schema/TypeKind.hs
src/Data/Morpheus/Types/GQLType.hs
src/Data/Morpheus/Types/ID.hs
src/Data/Morpheus/Types/Internal/Data.hs
src/Language/Morpheus.hs

Feature/Generate GQL Schema Document

---

src/Data/Morpheus/Kind.hs
src/Data/Morpheus/Resolve/Decode.hs
src/Data/Morpheus/Resolve/Encode.hs
src/Data/Morpheus/Types/GQLType.hs

Add a dedicated kind for Type Kinds in Data.Morpheus.Kind

---

src/Data/Morpheus/Resolve/Generics/EnumRep.hs

Just being picky.
These lines are basically identical, but later is more readable IMHO. :-)

Clean up: combine with pattern guard

---

changelog.md
examples/Main.hs
src/Data/Morpheus/Execution/Client/Selection.hs

Feature/GraphQL Client Support GraphQL Alias

---

changelog.md
src/Data/Morpheus/Document.hs
test/Feature/Holistic/API.gql
test/Feature/Holistic/API.hs

Feature/import GQL documents with Template Haskell

---

assets/simple.gql
changelog.md
examples/Client/Client.hs
src/Data/Morpheus/Execution/Client/Build.hs
src/Data/Morpheus/Execution/Client/Compile.hs
src/Data/Morpheus/Execution/Client/Selection.hs
src/Data/Morpheus/Execution/Internal/GraphScanner.hs
src/Data/Morpheus/Execution/Server/Introspect.hs
src/Data/Morpheus/Execution/Server/Resolve.hs
src/Data/Morpheus/Schema/SchemaAPI.hs
src/Data/Morpheus/Types/Internal/DataD.hs
src/Data/Morpheus/Types/Internal/Validation.hs

BugFix: GraphQL Client Defines enums and Input Types multiple times

---

src/Data/Morpheus/Execution/Client/Fetch.hs

Let me know if there's any issues!

Resolving issue 272 - Empty args sent as [] incorrectly

---

changelog.md
src/Data/Morpheus/Execution/Server/Interpreter.hs
src/Data/Morpheus/Execution/Server/Resolve.hs
src/Data/Morpheus/Execution/Subscription/ClientRegister.hs
src/Data/Morpheus/Server.hs

Allow users of subscriptions to use custom Monadic type--for creating socket apps--by providing function which goes from MonadIO => m to IO.

Implement generalization based on MonadIO

---

changelog.md
examples/package.yaml
examples/src/Server/MonadIO/API.hs
examples/src/Server/MonadIO/schema.graphql
src/Data/Morpheus/Types/Internal/Resolving/Resolver.hs

- Monad instance for resolvers
- Example using Monad transformers, STM, authentication.

Fun example

---

changelog.md
src/Data/Morpheus/Execution/Server/Encode.hs
src/Data/Morpheus/Types.hs
src/Data/Morpheus/Types/Internal/Resolving.hs
src/Data/Morpheus/Types/Internal/Resolving/Resolver.hs
test/Feature/Holistic/API.hs
test/Feature/WrappedTypeName/API.hs

Unexpose Resolver Constuctors

---

README.md
docs/index.md

Hi, I was reading through the docs and noticed some typos + grammar issues. Hopefully these changes are correct :)

Fix typos + grammar

---

README.md

This:
1. Provides another clarifying example of the same union written in two
styles, to show how the end result will be different
2. Switches to a more haskell-ey string comparison syntax (uses (<>)
instead of (+) to indicate concatination) in the inline comments
The motivation for this is provided in #389, where I got confused about how union deriving works.

Update README with more info on union types

---

changelog.md
src/Data/Morpheus/Types/ID.hs

Issue 411/Aeson instances for  ID

---

morpheus-graphql-core/changelog.md
morpheus-graphql-core/package.yaml

Issue 492/expose selection tree

---

changelog.md
morpheus-graphql-client/changelog.md
morpheus-graphql-client/src/Data/Morpheus/Client.hs
morpheus-graphql-client/test/Case/Github/Test.hs
morpheus-graphql-client/test/Case/JSON/Custom/Query.hs
morpheus-graphql-client/test/Case/LowercaseTypeName/Test.hs
morpheus-graphql-core/changelog.md
morpheus-graphql-core/morpheus-graphql-core.cabal
morpheus-graphql-core/package.yaml
morpheus-graphql-core/src/Data/Morpheus/Types/GQLScalar.hs
morpheus-graphql-core/src/Data/Morpheus/Types/GQLWrapper.hs
morpheus-graphql-core/src/Data/Morpheus/Types/ID.hs
morpheus-graphql-examples-client/src/Client/DefineByIntrospection.hs
morpheus-graphql-examples-client/src/Client/Mythology.hs
morpheus-graphql-examples-scotty/src/Client/Client.hs
morpheus-graphql-examples-scotty/src/Server/Sophisticated/API.hs
src/Data/Morpheus/Server/Deriving/Decode.hs
src/Data/Morpheus/Server/Deriving/Encode.hs
src/Data/Morpheus/Server/Deriving/Schema.hs
src/Data/Morpheus/Server/Internal/TH/Decode.hs
src/Data/Morpheus/Types.hs
test/Feature/Holistic/API.hs
test/Rendering/Schema.hs

Feature/ Encoder and Decoder classes for Scalar and Wrapper types

---

README.md

See [this discourse question](https://discourse.haskell.org/t/help-with-morpheus-graphql-example/2556?u=jaror)

Fix native Haskell types example in README

---

morpheus-graphql-client/changelog.md
morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Type.hs
morpheus-graphql-client/test/Case/Enum/response.json
morpheus-graphql-client/test/Case/Enum/schema.gql
morpheus-graphql-core/src/Data/Morpheus/Internal/Utils.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/Base.hs

fix(client): support lower case enums

---

morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/ResolverState.hs
morpheus-graphql-core/changelog.md
morpheus-graphql-core/src/Data/Morpheus/Error/Utils.hs
morpheus-graphql-core/src/Data/Morpheus/Parsing/Internal/Internal.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/Base.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/Validation/Validator.hs

feat(ast): extend GraphQL errors

---

changelog.md
morpheus-graphql-examples-scotty/src/Server/Mythology/API.hs
morpheus-graphql.cabal
src/Data/Morpheus/Server/Deriving/Decode.hs
src/Data/Morpheus/Server/Deriving/Schema.hs
src/Data/Morpheus/Server/Deriving/Schema/TypeContent.hs
src/Data/Morpheus/Server/Deriving/Utils.hs
src/Data/Morpheus/Server/Types/GQLType.hs
src/Data/Morpheus/Server/Types/Types.hs
src/Data/Morpheus/Types.hs
test/Feature/Inference/TaggedArguments.hs
test/Feature/Inference/TaggedArgumentsFail.hs
test/Feature/Inference/tagged-arguments-fail/introspection/query.gql
test/Feature/Inference/tagged-arguments-fail/introspection/response.json
test/Feature/Inference/tagged-arguments-fail/resolving/query.gql
test/Feature/Inference/tagged-arguments-fail/resolving/response.json
test/Feature/Inference/tagged-arguments/introspection/query.gql
test/Feature/Inference/tagged-arguments/introspection/response.json
test/Feature/Inference/tagged-arguments/resolving/query.gql
test/Feature/Inference/tagged-arguments/resolving/response.json
test/Spec.hs

feature(server): tagged arguments

---

docs/src/components/section.js
docs/src/pages/named-resolvers.mdx

feat(docs): finish named resolvers

---

examples/client/src/Client/DefineByIntrospection.hs
morpheus-graphql-app/src/Data/Morpheus/App.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Types.hs
morpheus-graphql-client/test/Case/JSON/Custom/Errors.hs
morpheus-graphql-client/test/Case/JSON/Custom/Errors/response.json
morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Printing/GQLType.hs
morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Printing/Render.hs
morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Printing/Terms.hs
morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Printing/Type.hs
morpheus-graphql-core/changelog.md
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/Error.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/TypeSystem.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/Validation/SchemaValidator.hs
morpheus-graphql-core/src/Data/Morpheus/Types/Internal/Validation/Scope.hs
morpheus-graphql-subscriptions/src/Data/Morpheus/Subscriptions/ClientConnectionStore.hs
morpheus-graphql-subscriptions/src/Data/Morpheus/Subscriptions/Stream.hs
morpheus-graphql/src/Data/Morpheus/NamedResolvers.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/App.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/Channels.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/Named/EncodeType.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/Named/EncodeValue.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/Utils.hs
morpheus-graphql/src/Data/Morpheus/Server/Deriving/Utils/GTraversable.hs
morpheus-graphql/src/Data/Morpheus/Types.hs

Fix Error path

---

README.md

remove docs

---

.github/workflows/publish-release.yaml

add github token

---

examples/client/morpheus-graphql-examples-client.cabal
examples/client/package.yaml
examples/code-gen/morpheus-graphql-examples-code-gen.cabal
examples/code-gen/package.yaml
examples/scotty/morpheus-graphql-examples-scotty.cabal
examples/scotty/package.yaml
examples/servant/morpheus-graphql-examples-servant.cabal
examples/servant/package.yaml
morpheus-graphql-app/morpheus-graphql-app.cabal
morpheus-graphql-app/package.yaml
morpheus-graphql-benchmarks/morpheus-graphql-benchmarks.cabal
morpheus-graphql-benchmarks/package.yaml
morpheus-graphql-client/morpheus-graphql-client.cabal
morpheus-graphql-client/package.yaml
morpheus-graphql-code-gen/morpheus-graphql-code-gen.cabal
morpheus-graphql-code-gen/package.yaml
morpheus-graphql-core/morpheus-graphql-core.cabal
morpheus-graphql-core/package.yaml
morpheus-graphql-subscriptions/morpheus-graphql-subscriptions.cabal
morpheus-graphql-subscriptions/package.yaml
morpheus-graphql-tests/morpheus-graphql-tests.cabal
morpheus-graphql-tests/package.yaml
morpheus-graphql/morpheus-graphql.cabal
morpheus-graphql/package.yaml

This change is necessary to build with ghc-9.2.2 from latest nixpkgs.

Allow bytestring-0.11

---

.github/workflows/draft-release.yaml
.github/workflows/haskell.yml
.github/workflows/pages.yml
.github/workflows/publish-release.yaml
morpheus-graphql-client/changelog.md
scripts/release.ts

migrate to main

---

morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Internal/AST.hs
morpheus-graphql-code-gen/src/Data/Morpheus/CodeGen/Interpreting/Transform.hs
morpheus-graphql/src/Data/Morpheus/Server/TH/Declare/GQLType.hs
morpheus-graphql/src/Data/Morpheus/Server/Types/GQLType.hs

- deprecated :  GQLType.getDirectives

Custom Directives API

---

README.md

Just a minor update to README.

Updating install instructions for 0.26.0

---

morpheus-graphql-client/README.md

This change removes deprecated TH.

Update client documentation

---

morpheus-graphql-app/morpheus-graphql-app.cabal
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Batching.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Cache.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Refs.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/ResolveValue.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/ResolverState.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/RootResolverValue.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Types.hs
morpheus-graphql-app/src/Data/Morpheus/App/Internal/Resolving/Utils.hs
stack.yaml

clean fix of https://github.com/morpheusgraphql/morpheus-graphql/pull/808

Refactor Named Resolvers

---

config/stack.yaml
morpheus-graphql-app/morpheus-graphql-app.cabal
morpheus-graphql-app/package.yaml
morpheus-graphql-client/morpheus-graphql-client.cabal
morpheus-graphql-client/package.yaml
morpheus-graphql-core/morpheus-graphql-core.cabal
morpheus-graphql-core/package.yaml
morpheus-graphql-server/morpheus-graphql-server.cabal
morpheus-graphql-server/package.yaml
morpheus-graphql-subscriptions/morpheus-graphql-subscriptions.cabal
morpheus-graphql-subscriptions/package.yaml
morpheus-graphql/morpheus-graphql.cabal
morpheus-graphql/package.yaml

This PR enables building the project with ghc-9.6.1

Allow transformers-0.7
